### ISSUE TITLE
add short code insertion option in tinymce

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#105]
add a toolbar icon that on click opens a window which enables inserting the shortcode into the content. The window should enable setting the id attribute of the shortcode.

The window should be displayed only for people that have the capability of (will think of a name). make sure admins in network have it by default.

For people with the capability, add a setting in the user profile to turn the feature off.

**Comment by markkap** [comment]
need to probably have better icon and support localization

**Comment by DanielFloeter** [comment]
It should be a link as the media link and don't  support only one specific editor plugin.
But if it, it's no code for the core code. It's custom code, as we do to work our plugin with other plugins.
Not all use or have this plugin installed and plugin dependencies make our code week.

**Comment by markkap** [comment]
what editor plugin?

**Comment by DanielFloeter** [comment]
TinyMCE is an editor plugin?

**Comment by markkap** [comment]
no tinymce is the editor ;)

**Comment by DanielFloeter** [comment]
With not good options, I know. They don't support shortcode

**Comment by markkap** [comment]
I don't understand ;) tinymce is the wordpress editor. it supports
shortcode in whatever way you want if you are willing to write a plugin
that does it

**Comment by DanielFloeter** [comment]
It was a joke. There are two tinymces: ultimate and advanced. The new automatic editor is in the jetpack backend, after logging on there site.

**Comment by markkap** [comment]
lol, I actually don't know much about jetpack, but at least the ultimate
and advance I know. :)

**Comment by markkap** [comment]
some design work probably needed on the button, but for now lets call this complete
