### ISSUE TITLE
move 'my settings" from the widget to the user profile

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#106]
use the name "accordion behavior for widget admin". Show only for users with theme settings permissions. this setting should be applied to all widgets

**Comment by markkap** [comment]
ooops duplicate

**Comment by DanielFloeter** [comment]
I think the User Profile is not a right place for widget settings. Instead it should be a new WP settings.

**Comment by markkap** [comment]
it has to be per user as your favourite settings are different than mine ;)

**Comment by DanielFloeter** [comment]
This make sense. Can we give a link from the widget to the use setting

**Comment by markkap** [comment]
sure

**Comment by DanielFloeter** [comment]
With #116 the link name is wrong. It's not all about the panels. Use a more generic name, like "Widget behaviour settings"
