### ISSUE TITLE
add post format indocation on top left of the thumbnail 

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#107]
many sites have some indication if the main content of the "post" is a video. lets adopt it, use the wordpress dash icons in the beginning to add a video play, music note, picture, and gallery icons when the post format is a relevant one.

**Comment by markkap** [comment]
on cnn you see it on bottom left. probably should be part of the title when there is no thumb?

@DanielFloeter do you think it is worth doing it, or leave it for 4.8?

**Comment by DanielFloeter** [comment]
I think in a abstract way and don't consider any  design layout (icon left, right, beneath the title) also the kind of the icon. So what's left is supporting icons - that's what I vote for.

Do it in the free with a good, not complex, default design layout. I'll expose for the premium some filer hook extension with icons.

We add a folder for icon sets? Where users can put own icon sets and we store the reference to this external icon set files in the DB (like choosing a image)

To support many kinds of icons (photo, gallery, video) the used icons could be set global for 'post formats' with settings or what I prefer as post widget to choose the icon for each post.

**Comment by markkap** [comment]
The idea I had was to use dashicons/genericons/font-awesome the user can
select which one they have or want to use. Then it should be easy to just
add the css for it. Use select2 to select which post formats to support but
select the "images" for them from the ones available in the font.

maybe just have implementation with dashicon and user can override it with
css?

moving to 4.8 for now, probably need to think more about this
