### ISSUE TITLE
Fluid images for small screens try with JavaScript

### ISSUE THREAD

**Issue by DanielFloeter** [tiptoppress/category-posts-widget#109]
The image size should only change if not enough space to fill out:

- Set width as max-width: PX and width: %
- Listen width is resized and calculate height with JS

(Listen the window resize event and recalculate image dimentions)

**Comment by markkap** [comment]
for top we know the width is 100%. we can try to add all images to srcset and let the browser select the best one (or use the picture html element?).

Height should probably be given in % of width, or an aspect ratio. 

IIRC we don't use css cropping on free, so maybe no JS is needed at all?

**Comment by DanielFloeter** [comment]
We should provide one function for one problem. And where we call this function and for what Style option is not the question of this isssue.

**Comment by markkap** [comment]
forgot the details ;)

**Comment by DanielFloeter** [comment]
We can plan a second if-else and do this when we support selecting 'custom-size' (added with add_image_size()) which includes WP's thumb, small, medium and large image_size.

**Comment by markkap** [comment]
there are actually many more sizes with each theme and some of the plugins
registering their own. I am not sure, maybe we should just try a 200 width
for sidebar and find the best matching image, and 500 for shortcode....
Another alternative is to try to use the html picture element but I am not
sure about browser support for it.

probably to let the user select the image is easiest, but using the picture
element can get the best results.

hmmm https://developer.mozilla.org/en/docs/Web/HTML/Element/picture I see
it is not a standard yet :( so long time before it can actually be used

**Comment by DanielFloeter** [comment]
Rename because: This issue is only for re-calculating the thumb dimensions. Image dimension re-calculating will be performed: Only if there is not enough space for the set thumb dimensions and if the Theme provides fluid widths for responsive layouts.
