### ISSUE TITLE
Both thumb dimensions can be left empty

### ISSUE THREAD

**Issue by DanielFloeter** [tiptoppress/category-posts-widget#113]
The aim is:
- all available space will be used for the image

Prozeed:
- the image sizes from the source image are used

**Comment by DanielFloeter** [comment]
ideas:
- add a option to select between image ratio and image size. In the UI this means change between px and %

**Comment by markkap** [comment]
@DanielFloeter ratio is better.... question is how do we let the user select it in the admin.... for top thumb maybe all we need is height as % of width.... for left thumb we need width or height in pixels/em/..., and the other can be in % of it

**Comment by DanielFloeter** [comment]
May a complicated feature also for the pro?

**Comment by DanielFloeter** [comment]
Duplicate of #205
