### ISSUE TITLE
make documentation links to point to a version specific URL on the site

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#115]
right now all versions point to the same one which makes it both harder to maintain and harder for the users which use older versions.

Since we should not have behaviour changes in a point release, lets have pages only for major release, so 4.7.1 and 4.7.2 will point to the same place while 4.8.1 to another

**Comment by DanielFloeter** [comment]
The documentation should should show the version number for no confusion.

The current version should be always the same because we don't want change all link references each time the version change.

Why not use a concept like GH with having /blob/ in the link name for the current version?

**Comment by markkap** [comment]
I am open to better suggestions.... but on GH they know what version you
are looking at now, and we don't know on our site which version the user
uses. Right now 40% of users running 4.6 and probably some of them are not
going to upgrade to 4.7 .... it is not the end of the world that they go to
the documentation for 4.7 and then need to find the link to the
documeentation of 4.6, but it is not very nice

**Comment by DanielFloeter** [comment]
Sorry, /blob/ is not correct. It means a object link.

The link on the webpage(s) should be the same, the /current/ version.
The links in a widget should be refere to the widget version documentation.

**Comment by markkap** [comment]
I don't understand.

right now the link is /category-posts/documentation
I wan it to be /category-posts/4.7

category-posts/current will not work well because we don't know what is the
current for the user, and it is basically what we have today.

**Comment by markkap** [comment]
reading again it seems that we agree.... ?

**Comment by DanielFloeter** [comment]
So the link is only the version number not the patch version.
I change it on WP.org and on tiptoppress.com

**Comment by markkap** [comment]
yes, we should not do new featuers in point release, so one documentation
for one main release should be enough
