### ISSUE TITLE
remove the css file. make all css be "local" to a specific widget

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#117]
need to check that all widgets have an id attribute and all the CSS is targeted for it.

as a side, add css for optional settings like hover effects only when needed

**Comment by DanielFloeter** [comment]
I'm not really understand the aim. My idea goes in this direction to add CSS classes to the HTML with PHP and have one external CSS file for all widgets

**Comment by markkap** [comment]
1. You should not load classes that are not used on the page. They waste time in both getting the CSS file and parsing it.

2. with general classes you still can have collisions with the code of other people that use the same class name. Right now we have a collision with the pro plugin

3. changes in CSS files can not be unit tested . If we had needed big CSS then it would have been a not very important factor, but our CSS file is very small.

**Comment by DanielFloeter** [comment]
1. People want use CSS minifier

2. We had a widget short name cpw_ and tcpw_. This should not a problem

3. We can't talk about things we don't have and use. For me CSS selectors in the PHP file is worse to maintain

4. For performance optimization one CSS file is a good solution: It's loaded one time to the browser cache and don't use bandwidth any more

5. People want change a external CSS file (included me ;) ). Ok, custom changes should go to the Child Theme CSS files, but exactly this is more difficult. Simple copy the widget CSS file to the Child Theme is not possible.

**Comment by markkap** [comment]
1. who? people must but no one "wants"

3. why is it worse? this is a problem with our code that we need to fix in our code.

4. no, any http request is worse then anything else you can do, especially when the file is so small

5. ok, this is a valid point ;) but not sure how many people do that instead of just fixing the rules they want

But the real problem that we need to solve is what happens when there are two widgets on the page one with css and the other without css.

**Comment by DanielFloeter** [comment]
We had one problem left? And there is no feature or solution which will solve external CSS files?
Is this right?

Can we rename the issue?
Because I want make a issue which "set CSS classes in the PHP file and assign all CSS selectors in a external CSS file"

All I can see is double CSS selectors per widget instance in the HTML output - > this is terrible in any cases: 
- loading Performance (not agree with: Load CSS file once to the browser cache), 
- for the customers which want change it, 
- us: we want maintain this code

**Comment by markkap** [comment]
for most sites css and js rarely load from cache. WordPress sites especially are small and their resources almost never get cached for long term. In any case long term cache requires server configuration changes that most people do not know how to do.

I am open to any suggestion that fixes the bug and do not load needless css rules. 

for reference

https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

If the external CSS resources are small, you can insert those directly into the HTML document, which is called inlining. Inlining small CSS in this way allows the browser to proceed with rendering the page.

https://gtmetrix.com/remove-unused-css.html

**Comment by DanielFloeter** [comment]
That's the point, our CSS is not small (max. five lines?) and have to put in an external file. And we double the CSS code as I mentioned above, when putting Inlining

**Comment by markkap** [comment]
our CSS is extremely small. especially when you take the hover effect that should not be there out of it.

How exactly we double the CSS code?

**Comment by markkap** [comment]
1. no they don't, they are being forced into that because every small
plugin adds JS and CSS without minifying them.

2. So what? Someone else can fork the widget and not change the names.
Anyway, the idea is not to remove class names from the element it the
widget.

4. a 50 line css file is bad performance for the site. on the front end and
server side. An http request takes long time on the browser side and it
overloads the server with another pointless request to handle

5. People don't know how and don't want to write CSS. This is a widget for
non technical people and non technical people find it hard to even create
child themes.

**Comment by markkap** [comment]
seems like page builders have problems with providing the same IDs as it is done in most (all?) themes in the sidebar. This means that we need to put an ID on the UL itself. @DanielFloeter, any reason not to do it (add id on the ul)?

**Comment by DanielFloeter** [comment]
Additional is good. But is there not yet an Id associated to the UL?

**Comment by markkap** [comment]
no, on pro we expect wordpress core to put a proper id on the div containing the widget. It probably works with all themes because they register correctly the sidebar to include the id

Another option is to do an id on the UL something like "_categoryposts_internal"
