### ISSUE TITLE
"fluid" thumbnails do not work on themes without jquery

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#119]
for example twentyten https://wordpress.org/themes/twentyten/ with 300k active sites do not enqueue jquery. same with twentyeleven

**Comment by DanielFloeter** [comment]
So this is not a problem of this feature. ''Tis is a problem of the hole widget?

**Comment by markkap** [comment]
where else don we have dependency on jquery on the front end? Where we have we enqueue jquery ourself (bxslider) or indirectly with masonry, but we never assume it is there.

I will hate to enqueue jquery just for this, but seems like every site will add it at some point :(, so this can be a solution until people complain. But like the other ticket if we enqueue jquery it should be only when we know that the JS code is actually needed

**Comment by DanielFloeter** [comment]
Problem for the hole widget
