### ISSUE TITLE
fluid JS in added when it is not needed

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#120]
should be added for only widgets with thumbs on and cropping on (?). Probably better to trigger adding it to the footer from the "show thumbnail" functions.

and footer_script is really bad name for a function ;) maybe add_fluid_script is better?

**Comment by DanielFloeter** [comment]
Solve this with #113 and #112 

The name is from the pro and add all script to the footer? Don't know what the problem is? 
(Plz, one issue one problem.)

**Comment by markkap** [comment]
I don't understand how those issues are related to this one. we should add JS code only when needed

**Comment by DanielFloeter** [comment]
Also #110

**Comment by markkap** [comment]
that doesn't answer my question :( if someone do not have thumbs why should this JS be in his HTML?
