### ISSUE TITLE
Excerpts should pull from "excerpts"

### ISSUE THREAD

**Issue by TimTimothy** [tiptoppress/category-posts-widget#130]
When I select to have excerpts included, your widget pulls from the first words in the article, rather than from the "excerpt" box below my post. This would be much preferred, as I set up custom excerpts for my posts.

**Comment by markkap** [comment]
This is a big oops, it should work like that. Will look at it ASAP

**Comment by DanielFloeter** [comment]
@TimTimothy Please try to check the "Themes and plugins may override" option in the Post details panel. This solves you problem.

All settings are filters which overrides the WordPress standard behaviour, if you want to use the settings (excerpt length and more-text) from the widget.

We write a blog post how we support the excerpt and we provide a own extension widget for the premium version to overriding/using the Wordpress/Plugins/Themes excerpt: http://tiptoppress.com/term-posts-excerpt-extension/

You're welcome to have a option and write us again. But as mentioned the descriped option above should work for you.
