### ISSUE TITLE
Privately published posts missing

### ISSUE THREAD

**Issue by Vistra** [tiptoppress/category-posts-widget#157]
Privately published posts are no longer displayed after updating to version 4.7.3.

something like this seems to work:

if (current_user_can('read_private_posts')) {
  $args['post_status'] = array_push($args['post_status'], 'private');
}

**Comment by DanielFloeter** [comment]
Is it possible you test the commit which is available at the 4.7.3 branch?
It's the current version on wordpress.org: https://github.com/tiptoppress/category-posts-widget/tree/4.7.3

**Comment by Vistra** [comment]
The problem with this solution is that the links to private posts are still being displayed even if I'm not logged in.

**Comment by DanielFloeter** [comment]
Is it possible to test again: https://github.com/tiptoppress/category-posts-widget/tree/4.7.4

**Comment by Vistra** [comment]
This works! Thank you!

**Comment by DanielFloeter** [comment]
We had released the version on wordpress.org. Thanks.
