### ISSUE TITLE
investigate the use of object-fit:cover CSS property for thumbnails

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#158]
https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

https://caniuse.com/#feat=object-fit says it is supported for 90% of users right now. The biggest problem is with edge/IE not supporting it, or supporting only partially

The idea is to replace our current hacky margin calculation done to crop the images on the front end with simple CSS.

**Comment by markkap** [comment]
After looking at it, either I do not understand how to use it in our context, or it does not gain us almost anything

**Comment by DanielFloeter** [comment]
It is used in the Gutenberg gallery so the browser support can be getting ok
