### ISSUE TITLE
Release 4.8.1 won't accept title with excerpt template

### ISSUE THREAD

**Issue by jimmy-carter** [tiptoppress/category-posts-widget#168]
Post details revert to "Only the Title" upon save. Excert showsk in post, but will not align beside the thumbnail. Only below it.

**Comment by DanielFloeter** [comment]
Do you add a new widget instance with within a open customizer to your widget area?

We know this issue #166 but up to now we don't found the bug. 

All we know is a workaround when you add the widget with the customizer: Change any setting and save the widget. Then you can use all post detail settings and the Template feature as described.

**Comment by jimmy-carter** [comment]
I was using the plugin in a widgetized area of a page with SiteOrigin PageBuilder.

**Comment by DanielFloeter** [comment]
Can you test the [4.8.2 branch](https://github.com/tiptoppress/category-posts-widget/tree/4.8.2) if your bug is fixed?
