### ISSUE TITLE
When caculating the ratio to be used in the cropping JS make sure height is not zero

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#174]
If for some reason the user have it zero, just do not do cropping for that image.

**Comment by DanielFloeter** [comment]
Very cool feature

**Comment by DanielFloeter** [comment]
Make clear in the template the placeholder to show feature images is used

**Comment by DanielFloeter** [comment]
I recommend to label this as bug as @adnaniub write on wp.org: https://wordpress.org/support/topic/php-warning-division-by-zero-in-category-posts-cat-posts-php-on-line-1320/
