### ISSUE TITLE
remove the "allow html" and "hide social" in excerpt funcionality

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#180]

**Comment by markkap** [comment]
hmmm add the hiding of social buttons to it

**Comment by markkap** [comment]
@DanielFloeter I left the apply_the_excerpt function, not sure if it is needed

**Comment by DanielFloeter** [comment]
We use the filter in the Excerpt Extension.
120% important.

@markkap Can it be a option to leave in the function head commend were we use the filter in our Extensions?

**Comment by markkap** [comment]
hmm, ok, can you look at the code? I removed only the functions that
depended on the widget configuration options
