### ISSUE TITLE
Accessing template for recent posts widget?

### ISSUE THREAD

**Issue by socialmediums** [tiptoppress/category-posts-widget#201]
The styling of the `default` template in the plugin leaves our list of recent posts on our front home page looking like this:

![image](https://user-images.githubusercontent.com/54753059/70270878-41276480-1773-11ea-95e3-6ebb8fd7a42a.png)

Since it's not very appealing, we wanted to access and create a new template for the list of templates:

![image](https://user-images.githubusercontent.com/54753059/70270909-53a19e00-1773-11ea-92bc-dfd75b24a538.png)

However, we can't figure out where those settings live in the Dashboard. Can you please help?

**Comment by DanielFloeter** [comment]
Sorry, but I guess you are wrong here. That screenshot looks not like our widget? You are sure about that request.

**Comment by socialmediums** [comment]
You're completely right - we had a different plugin that was conflicting with your shortcode and it looks as though the page didn't know which plugin to prioritize!
