### ISSUE TITLE
no category filter

### ISSUE THREAD

**Issue by vianmora** [tiptoppress/category-posts-widget#203]
Hello, I'm on Wordpress 5.4  with the Optimizer theme and when I launch the category-post widget, I have on the customizer the following message : 

Warning : Invalid argument supplied for foreach() in .../front-posts.php on line 203

**Comment by DanielFloeter** [comment]
Hello @vianmora, do you really mean our widget? We haven't a .../front-posts.php file.
Do you have deactivate our widget and the issue is gone?

We test against the WordPress 5.4 since the week it was released and there are no issues known for use

**Comment by vianmora** [comment]
Hello, sorry, i was using the widget of my theme (Optimizer)

you widget works well ! thank you ! ;) 

Have a good day and thanks for your reactivity :D 

Vianney MORAIN

**Comment by DanielFloeter** [comment]
Thank you, too.
Good thing we were able to solve it.
