### ISSUE TITLE
The slider does not work with Wordpress 5.5

### ISSUE THREAD

**Issue by PatrickKzing** [tiptoppress/category-posts-widget#204]
After an update to Wordpress 5.5 the slider and the masonary style is not working anymore.

**Comment by DanielFloeter** [comment]
Hello @PatrickKzing, you have the pro version in mine. We patch that issue about WordPress 5.5. for the slider. Are you interested in a test version? Please write to us at http://tiptoppress.com/contact/ and also can you send us an Url where the Masonry doesn't work?

**Comment by DanielFloeter** [comment]
For us WordPress 5.5 works with the slider, the news ticker and masonry.
We read some about WordPress don't support jQuery Migrate 1.x anymore.
You can try to enable it with that plugin: https://wordpress.org/plugins/enable-jquery-migrate-helper/
It can also be an issue with your Theme which want support an older jQuery version.
