### ISSUE TITLE
Add shortcode.

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#45]
[catposts id=xxxx] ? 

We can do a long list of options in attributes, but it is not very easy to use. Maybe hook into the customizer so the user adds the shortcode in the text and configure it in the customizer?

other ideas?

**Comment by markkap** [comment]
Inspired by the "shortcode widget" plugin we can create a virtual sidebar of "In content Cat posts", and automatically add and remove widgets to it. once we detect them in the code (and remove once the post is deleted).. An optional ID attribute can be given to differentiate between sidebars in the same post

Customizing the widget is done in the admin interface or the customizer. No special menu in the editor, just a notice when we detect a widget in the content that direct people to use the customizer to edit it

**Comment by DanielFloeter** [comment]
Very nice feature which can improve the widget and the configuration in the WP maintained way. Preconditions are a horizontal slider, the issue on BB: Options (CSS) for Styles set for each widget instance and a decision which Styles we merge to the free.

**Comment by markkap** [comment]
I don't think that a slider is a must, what this can be used for without a slider is for example show latest 3 news/blog articles in an full width "about us" page, or maybe "one page" type of websites where there is no sidebar and it might not be easy to add one.

But yes this is an "advanced" type of feature, but people do ask for it, and then in the pro it cn be combined with a slider :)
