### ISSUE TITLE
allow users to format the the order of the components

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#49]
For example, for some people maybe the date should be before the excerpt.

We can add some easy options in a dropdown and also let the user use a sprintf style format.

**Comment by markkap** [comment]
Template syntax

Everything that might be a link by defaults link to its appropriate page (author to author archive, comments to comments in the posts, tags to the tags archive etc.).
\n => a space
\n\n => next line is a P element
%title% => the post title
%date% => date based on the requested format
%excerpt% => the excerpt. Due to the way we calculate excerpts it is always in a P
%commentnum% => The number of comments in (N) format
%author% => the display name of the author
%tag% => a list of the tags associated with the post, separated by commas
%category% => a list of the categories associated with the post, separated by commas

any text which is not a template is used as it is.

Default template - %title%

example of template
%title%
\n\n
%excerpt%
\n\n
Categories: %category%

will result in a title displayed above the excerpt, and the list of categories below like
```
This is a post
a post about nothing
Categories: Uncategoriesed
```

**Comment by DanielFloeter** [comment]
Very helpful

**Comment by markkap** [comment]
and again bad me for not associating all the commits....
