### ISSUE TITLE
minify JS and and CSS files

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#50]
Serve the unminified when WP_DEBUG is on, otherwise serve minified

**Comment by markkap** [comment]
closing as we don;t have big enough files to be worthy of the trouble

**Comment by DanielFloeter** [comment]
There're other widgets which do minification, gathering files, make asynchron calls, put the call to the button, etc.
It will be a nice to have, but not for many users.

We can try writing a filter/hook wich do that. If a user wants we can refer to this filter/hook?

**Comment by markkap** [comment]
no one complained so far and I want to remove the CSS file in any case ;)
it is actually easy to add to a build tool a minification option, but we
will need to first have a build tool :) too much work for small files
