### ISSUE TITLE
Adapt existing FAQ entry for 'Disable CSS' if more then one instances on page

### ISSUE THREAD

**Issue by DanielFloeter** [tiptoppress/category-posts-widget#52]
Existing:
The font-size is different from that of other widgets or Theme elements?
Please use the option: "Disable widget CSS".

Adapt:
If you use more then one instance on your site, you have to unchecked this option on all used widgets.

**Comment by markkap** [comment]
I think we just should call it a bug, and see how can we change the classes that we use to handle it better. On a "with css" widget put a class and use it in all the default styling.

But this is going to be dangerous change, so lets wait until someone actually have such a situation and complains?

**Comment by DanielFloeter** [comment]
We can 'detect' if one or more checks for the option 'disable CSS' different. Then write it to the admin panel.

**Comment by DanielFloeter** [comment]
We use category_posts_iterator() for detecting different checks for option 'disable CSS'.

**Comment by markkap** [comment]
in the customizer there is no centralized place to writ it to, and it
actually can make sense to have one widget with default style and another
with different one. Lets say if someone uses woosidebars to have different
widgets on the blog and on the shop.

we just need more specific css classes if we want to do it 100% right.

How many people do you think use the default and how many add styling by
themself?

**Comment by DanielFloeter** [comment]
I can only estimate. There are many how asked how to disable, the other leave the default widget CSS. I say ~50:~50.

Here a user want diferent different title background colors for each instance: #40 
I vote for his proposal.

**Comment by markkap** [comment]
I agree, and then we can also simplify the code and not load the CSS file.
Do you think moving all the styling in the css to the widget will be hard
to do?
