### ISSUE TITLE
siteorigin page builder integration

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#55]
lol technically I have no idea what does it actually mean :)

**Comment by DanielFloeter** [comment]
Technically there is nothing to do that the widget can be used with Siteorigin page builder. It is a drag&drop UI and works with all widgets as you can drag&drop to the sidebar. The work comes with CSS. Page builder is a responsive plugin. So the idea is to test Category Posts Widget with Siteorigion page builder when providing responsive functionality and features.

**Comment by markkap** [comment]
The admin side looks bad, no select2 for example.
Not sure what you mean about responsiveness, the widget itself can not be responsive, only the layout that contains it

**Comment by markkap** [comment]
There is also some section dividers in siteorigin, we should probably adjust our css to take advantage of it

**Comment by DanielFloeter** [comment]
With page builder you can place the widget where ever you want and in any sizes to your site. We have to provide not only one width, like width for the sidebar. Maybe a horizontal ticker for hole site width. All for the website not the admin panel. The admin panel and how it looks like will be a separate issue, nothing to do with page builder at the main focus.

**Comment by markkap** [comment]
ok, fair enough, but I thought that the widget just expand to fill the content area assigned in the builder. As far as I remember we don't  set a width to the widget, just fill the width provided by the sidebar

**Comment by markkap** [comment]
@DanielFloeter unless you object our official solution for this going to be the shortcode #45 and we not going to try to support the select2 and other JS to work nicely in the builders.

**Comment by DanielFloeter** [comment]
We can open a new issue if we have technicaly more specifications for siteorigion page builder.
