### ISSUE TITLE
Options (CSS) for Styles set for each widget instance

### ISSUE THREAD

**Issue by DanielFloeter** [tiptoppress/category-posts-widget#65]

**Comment by markkap** [comment]
Lets define that for 4.6 the goal is to replace as much of the CSS file as we can with inline styles that the user can change

Easy first thing is the hover effects, need to let the user define speed, scale and opacity.
Not sure why do we need the following rule and it is not part of general thumbnail settings

li a.cat-post-white,
li a.cat-post-dark,
li a.cat-post-scale {
    background-color: black;
	display: inline-block;
    float: left;
	margin: 5px 10px 5px 0;
}

margin for sure needs to be in the thumbnail settings.

**Comment by DanielFloeter** [comment]
CSS styles can set for each widget instance
