### ISSUE TITLE
Give an option of not applying theme/plugin filters to excerpts

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#80]
Since we are using the general filters and general API for excerpt generation we might end up in collision with themes and plugins. This might be a good thing or not, maybe we should give the user an option to select. 

For example on 2014 theme, the theme uses a relatively long "continue reading" text as default in probably a filter and this might not be the best thing if the widget is in a small place.

We can think on a systematic solution or just one item at a time for example if the more text is set then ignore other filters and same with word number. This will leave us with mainly the generated excerpt text to worry about

**Comment by markkap** [comment]
@DanielFloeter I think I reached a decision of what I think is best to do, need to know what you think. 

For 4.7 we soft deprecate the old behavior without adding options. People that activated the plugin before 4.7 will keep using excerpt filter, but people that activate it on 4.7 will  not use filters. This way we don't break old site, but give a better functionality to new ones.

**Comment by DanielFloeter** [comment]
The problem we had is only for the_excerpt() or the_content()
Other excerpt filters are not included for this issues, like "excerpt_more" and "excerpt_length". If you delete all excerpt filters is like turn widget on/off.

So an option which apply or this to filters the_excerpt() and the_content() can be a solution. But as mentioned, this option do nothing with "excerpt_more" and "excerpt_length" or other excerpt filters.

**Comment by markkap** [comment]
why excerpt_length is different than the_excerpt? why would you want to style the excerpt in the widget exactly the same way as it is styled in the archive pages? Why do you want to let plugins override the settings of the widget by mistake?

**Comment by DanielFloeter** [comment]
We change the excerpt not the first time. But adding a option to disable the excerpt length is already available also for the more tag. We need it only for the the_excerpt and the_content?

**Comment by markkap** [comment]
we have decided to give user an option to select between an implementation that uses the_excerpt filter and one that directly calls wp_trim_words

**Comment by markkap** [comment]
@DanielFloeter can you test it and if it works for you, lets close this isuue
