### ISSUE TITLE
explicite_the_excerpt is not in english ;)

### ISSUE THREAD

**Issue by markkap** [tiptoppress/category-posts-widget#86]
not sure what it should be called but it is impossible to guess what it does.It needs also a better phpdoc style description

**Comment by DanielFloeter** [comment]
It was an issue from WP.org:
[https://wordpress.org/support/topic/jetpack-sharing-options-showing-in-widget](https://wordpress.org/support/topic/jetpack-sharing-options-showing-in-widget)

**Comment by DanielFloeter** [comment]
Add a option in General area 'hide/show social buttons on output'
