### ISSUE TITLE
Write posts and news to WordPress admin Dashboard

### ISSUE THREAD

**Issue by DanielFloeter** [tiptoppress/category-posts-widget#90]
- TipTopPress news and posts

- Register to newsletter badget

- ...

**Comment by markkap** [comment]
I think we should avoid doing things which are more complex than a link, so maybe add a link to the blog and first we need a newsletter ;)

**Comment by DanielFloeter** [comment]
If tiptoppress had more features we will consider to bring this to our customers.

**Comment by markkap** [comment]
the problem with showing things in admin is that most users do not enter the admin, especially not the widget area. I think people want in general to know if there are changes in the plugins they use especially when there is an update. The trick is to keep it informative and useful to the user and not only as a promossion
