### ISSUE TITLE
Divide by zero bug, if physical thumbnail file deleted and only in database

### ISSUE THREAD

**Issue by DanielFloeter** [tiptoppress/category-posts-widget#95]
https://wordpress.org/support/topic/warning-division-by-zero-pluginscategory-postscat-postsphp-on-line-295

**Comment by markkap** [comment]
@DanielFloeter , Isn't this fixed already?

**Comment by DanielFloeter** [comment]
I didn't know at all that there is this task.

We had a pull request from [https://github.com/boligolov](boligolov) which we had to rework and merge it to 4.7: https://github.com/tiptoppress/category-posts-widget/commit/ba18551ccbf4fb98eb76fd606405568899a9ebad

The rework should be set a default image for this case of divide by zero but: https://github.com/tiptoppress/category-posts-widget/issues/56

**Comment by markkap** [comment]
there is a temptation to try to find different file, but in my opinion if someone have delete files in the wrong way, we can just end up with no file in any case. maybe should add some error about the need to regenarte thumbnails.... but later
